<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

    public function findCategoryGroup($category,$limit){
        return $this
            ->createQueryBuilder('n')
            ->select('n')
            ->where('n.category = :category')
            ->andWhere('n.visible = :show')
            ->setParameter('category',$category)
            ->setParameter('show',1)
            ->orderBy('n.id', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

}
