app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#sylius_cart:
 #   resource: "@SyliusCartBundle/Resources/config/routing.yml"




 #user_one_registration:
     #pattern:  /register/employee
  #   defaults: { _controller: AppBundle:Employee:register }

user_two_registration:
    pattern:  /register/customer
    defaults: { _controller: AppBundle:Customer:register }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
