app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#sylius_cart:
    resource: "@SyliusCartBundle/Resources/config/routing.yml"


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"