# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:
  sylius.model.sequence.class: Sylius\Component\Sequence\Model\Sequence

services:
  app.order_number_listener:
    class: Sylius\Bundle\OrderBundle\EventListener\OrderNumberListener
    arguments:
      - "@sylius.sequence.doctrine_number_listener"
    tags:
      - { name: kernel.event_listener, event: app.product_ordered, method: generateOrderNumber }

  app.cart_item_resolver:
           class:        AppBundle\Service\Cart\ItemResolver
           arguments:
             - "@doctrine.orm.entity_manager"


  pagerfanta.view.security:
      class: Pagerfanta\View\OptionableView
      arguments:
          - @pagerfanta.view.default
          - { proximity: 2, previous_message: Anterior, next_message: Siguiente }
      public: false
      tags: [{ name: pagerfanta.view, alias: security }]
  pagerfanta.view.address:
      class: Pagerfanta\View\OptionableView
      arguments:
          - @pagerfanta.view.default
          - { proximity: 5 }
      public: false
      tags: [{ name: pagerfanta.view, alias: address }]
  pagerfanta.view.shipping:
      class: Pagerfanta\View\OptionableView
      arguments:
          - @pagerfanta.view.default
          - { proximity: 5 }
      public: false
      tags: [{ name: pagerfanta.view, alias: shipping }]
  pagerfanta.view.payment:
      class: Pagerfanta\View\OptionableView
      arguments:
          - @pagerfanta.view.default
          - { proximity: 5 }
      public: false
      tags: [{ name: pagerfanta.view, alias: payment }]
  pagerfanta.view.confirm:
      class: Pagerfanta\View\OptionableView
      arguments:
          - @pagerfanta.view.default
          - { proximity: 5 }
      public: false
      tags: [{ name: pagerfanta.view, alias: confirm }]