# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:
  sylius.model.sequence.class: Sylius\Component\Sequence\Model\Sequence

services:
  app.order_number_listener:
    class: Sylius\Bundle\OrderBundle\EventListener\OrderNumberListener
    arguments:
      - "@sylius.sequence.doctrine_number_listener"
    tags:
      - { name: kernel.event_listener, event: app.product_ordered, method: generateOrderNumber }

  app.cart_item_resolver:
           class:        AppBundle\Service\Cart\ItemResolver
           arguments:
             - "@doctrine.orm.entity_manager"
             - "@form.factory"

